version: '3'

services:
  app:
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    container_name: docker-dotnetcore
    tty: true
    ports:
      - 10080:80
      - 10433:433
    volumes:
      - ./src:/usr/src
    working_dir: "/usr/src"